console.log("+--------+  +----+  +        +------+  X     X    +--------+   +------x\n")
console.log("    ||      |    |  |        |          X   X         ||       |\n")
console.log("    ||      |    |  |        +---+       X X          ||       +---x\n")
console.log("    ||      |    |  |        |            X           ||       |\n")
console.log("    ||      |    |  |        |           X X          ||       |\n")
console.log("    ||      |    |  |        |          X   X         ||       |\n")
console.log("    ++      +----+  +-----+  +         X     X   XX   ++       +\n")